apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-nginx-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-nginx-frontend
  template:
    metadata:
      labels:
        app: resume-nginx-frontend
    spec:
      containers:
      - name: resume-nginx-frontend-container
        image: coooolkpk/my-resume-in-react
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume-nginx-frontend
spec:
  type: NodePort
  selector:
    app: resume-nginx-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100

