apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  #replicas: 1  #commented replicas count because it was conflicting with hpa and argocd
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: coooolkpk/todo-app-backend:v1
        ports:
        - containerPort: 5000
        resources:
          limits: 
            cpu: 700m
          requests:
            cpu: 500m
        env:
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          value: "mongodb+srv://pico:Kavi2003@cluster0.0eiuu.mongodb.net/" 
        - name: DB_NAME
          value: "todo_app_db"


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
