apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb-service"
  #replicas: 1 #commented replicas count because it was conflicting with hpa and argocd
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            cpu: 1500m
          requests:
            cpu: 1000m
      volumes: 
      - name: mongodb-persistent-storage 
        persistentVolumeClaim:
          claimName: mongodb-pvc 
  #volumeClaimTemplates:
  #- metadata:
  #    name: mongodb-persistent-storage
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 
  volumeName: mongodb-pv 

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /home/pico/mongo 