apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  #replicas: 1 #commented replicas count because it was conflicting with hpa and argocd
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: coooolkpk/todo-app-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits: 
            cpu: 300m
          requests:
            cpu: 200m


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

