apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeed-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openspeedtest-app
  template:
    metadata:
      labels:
        app: openspeedtest-app
    spec:
      containers:
      - name: openspeedtest
        image: openspeedtest/latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest-app
spec:
  type: NodePort
  selector:
    app: openspeedtest-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003

