---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed-deployment
  labels:
    app: librespeedtest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeedtest-app
  template:
    metadata:
      labels:
        app: librespeedtest-app
    spec:
      containers:
      - name: librespeed
        image: lscr.io/linuxserver/librespeed:latest
        resources:
          requests:
            memory: "150Mi"
            cpu: "350m"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Asia/Kolkata
        - name: CUSTOM_RESULTS
          value: "true"
        - name: IPINFO_APIKEY
          value: 00bd2f4bcceaf8

